### ISSUE TITLE
Which is your preferred module bundler for angular 1.x projects?

### ISSUE THREAD

**Issue by floriangosse** [toddmotto/ama#1]

**Comment by toddmotto** [comment]
Webpack for sure (CommonJS). Even better with ES6 transpiling :)

**Comment by floriangosse** [comment]
What are the benefits compared to Browserify or SystemJS?

**Comment by toddmotto** [comment]
This post actually clears a lot up on comparisons: http://blog.namangoel.com/browserify-vs-webpack-js-drama

**Comment by floriangosse** [comment]
Oh sry. I forgot to close this question. I had no time to read the article. :-s
