### ISSUE TITLE
Source versioning control

### ISSUE THREAD

**Issue by ConstantinChirila** [toddmotto/ama#11]
Do you use for your private projects, other SVN than Github? Or you mostly use their paid version? I was thinking something that can sit on my server (or local machine).
Thank you!
Constantin

**Comment by toddmotto** [comment]
I use BitBucket for "ideas" that I have for private projects, anything I move into dev mode I keep in private on GitHub, just helps me organise things better :)

**Comment by ConstantinChirila** [comment]
Cool, thank you!
