### ISSUE TITLE
Diet

### ISSUE THREAD

**Issue by AlbertoBlas** [toddmotto/ama#14]
When we are developers, we are not shape because pizza, beer, coffee and long times sitting in front the computer doing something that we love.

What is the best way to achieve a good health and shape? Can you share us your diet?

Sorry for my bad english. Greetings from Mexico! :)

**Comment by toddmotto** [comment]
Hello there! So I got asked this question so much that I actually did a write up about it, any questions feel free to fire away: https://toddmotto.com/being-a-healthy-software-engineer
