### ISSUE TITLE
Getting started with front end dev

### ISSUE THREAD

**Issue by jmckirgan** [toddmotto/ama#16]

**Comment by toddmotto** [comment]
Hey dude, I think there was a question here - I am planning on answering so please add it back if you like. Just incredibly stacked at moment :)

**Comment by jonnymckirgan** [comment]
Ah ok!  Well I partly deleted it because I thought it was a stupid question or at least could do with re-wording, so I'll add a new question to this thread shortly.

**Comment by jmckirgan** [comment]
Hi Todd
I was wondering what your recommended approach would be to someone who wishes to become a professional front end developer.  Eg to learn JS before Angular (or simultaneously). It's basically about how to get from 0 to a point where one can understand articles covering Angular/React and knowing enough to be able to make a judgement as to what is the right tool for the job. And if you were starting over again, would you do things differently?
Cheers, Jonny
