### ISSUE TITLE
What advice would you give to me or your younger self?

### ISSUE THREAD

**Issue by vblazenka** [toddmotto/ama#19]
Hi, my name is Vedran. I am 19 years old, I decided not to go to college and pursue my career in IT industry. I'm currently working at the small local company in Zagreb, Croatia as Front-End Developer.

Now I will bother you with my small story. Sorry!

Some people are asking me why I don't go to college, well my answer is always that college can't feed my "learning hunger" (10-15 years old school system in my school).
I need to admit that I feel cursed, I can't focus on one thing... I love cutting edge technologies and learning them. In the past 6 years, I have tried everything from game dev, design, 3d design, backend, frontend... And I can see myself in any role if I want to.

In the past year and a half I decided to pursue FrontEnd/JavaScript while working as an intern in [Bellabeat](http://techcrunch.com/2014/05/23/bellabeat-lands-4-5m-to-grow-its-quantified-self-program-for-pregnancy/). Since then I was working with Angular and basic frontend stuff, at the current job I'm switching to ReactJS, and on the side I'm trying to learn iOS development. Can you see my problem?

I don't want to be Jack of all trades, master of none. 

My question is, what would your advice be to me, or your younger self regarding focusing on his career and moderate my "learning hunger"?

**Comment by toddmotto** [comment]
Hey Vedran! Thanks for stopping by, and such a great question. I think it's natural to feel this way, there's a tonne of things I really want to learn and "don't have time" for. I think it's just how developers are.

I decided not to study Computer Science or other related courses, and started as a junior front-end developer, and 5 years later have been the lead front-end engineer at two companies - and even started my own side project to give workshops and teach others JS/Angular etc online.

Front-end is rapidly changing, and is really exciting - so I'd focus on making sure your skills there are absolutely incredible. There's still so much I've yet to learn and want to get better at, and that'll never stop. JavaScript is a huge platform for experimentation, things like React and React Native are among the things I want to dive into further next.

I guess my answer would be stick to what you love - it could be JavaScript related, and therefore you can cross-over into backend development with Node etc. You've also got React Native for mobile development. You're in a good place asking these questions for sure, so I'm hoping my answer gives you some help :) master the things you know you want to master, and dabble in things you want to know how it works.
