### ISSUE TITLE
Contact form re-use

### ISSUE THREAD

**Issue by SvenKortekaas** [toddmotto/ama#21]
Hey Todd Motto,

I would like to use your [contact form](https://github.com/toddmotto/toddmotto.github.io/tree/master/labs/html5-contact-form) as a base, add some features and post it as a project under the GPL-3.0 License here on GitHub. Am I allowed to do that?

**Comment by toddmotto** [comment]
Hey @SvenKortekaas ! Yeah for sure, it's well old though, some updated practices might be good to add as well. Use as you wish :)
