### ISSUE TITLE
Targeting all elements of a Javascript array

### ISSUE THREAD

**Issue by whizkydee** [toddmotto/ama#22]
Hi @toddmotto,
I have a JS array and i want to target all the elements, i mean all the content so that i can apply the jQuery .remove method to remove the elements in the array.

I have something like this
`var arr = [
  $( "article" ).first(),
  $( "aside" ),
  $( "footer" )
];

arr.remove(); // Returns: TypeError: arr.remove is not a function `

// I want to apply the jQuery .remove method to the array,
// so that the elements would be removed.`

**Comment by toddmotto** [comment]
Not really sure what you mean or are trying to do here, some working could would be ideal.

**Comment by whizkydee** [comment]
Thanks @toddmotto I mean how do i run a code on all the items in an array. 
Like:

```
var arr = [
$( "article" ).first(),
$( "aside" ),
$( "footer" )
];
```

and i want to remove all these elements from the DOM, so i listed them in an array so that i would be able to select all of them at once.

**Comment by mxstbr** [comment]
``` JS
arr.map(($elem) => {
  $elem.remove();
});
```

**Comment by whizkydee** [comment]
@mxstbr, i'll try that... That's ES6. Thanks anyways.

**Comment by whizkydee** [comment]
Nice @mxstbr, that's cool. I tried it and it worked pretty fine. I never came across the .map method.
Thanks a lot.
Appreciates.

**Comment by mxstbr** [comment]
Works without ES6 too! :+1:

```
arr.map(function ($elem) {
  $elem.remove();
});
```

**Comment by toddmotto** [comment]
P.S @mxstbr you coulda rolled with 

``` js
arr.map($elem => $elem.remove());
```

**Comment by whizkydee** [comment]
@toddmotto that's quite short. How i love ES6.

**Comment by toddmotto** [comment]
Indeed. However unless you're doing something with the returned collection, I'd use `.forEach` over `.map` as map constructs and returns a new Array with the manipulated values, in this case an empty Array.

**Comment by whizkydee** [comment]
@toddmotto Oh. But do they have the same syntax, and which is better in Performance.

**Comment by toddmotto** [comment]
But they don't do the same thing

On 10 April 2016 at 21:54, Olaolu Olawuyi notifications@github.com wrote:

> @toddmotto https://github.com/toddmotto Oh. But do they have the same
> syntax, and which is better in Performance.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/toddmotto/ama/issues/22#issuecomment-208068990

## 

@toddmotto

**Comment by whizkydee** [comment]
Thanks @toddmotto, So what's different?

**Comment by toddmotto** [comment]
Check MDN:

forEach:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
map:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/map

On 10 April 2016 at 22:04, Olaolu Olawuyi notifications@github.com wrote:

> Thanks @toddmotto https://github.com/toddmotto, So what's different.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/toddmotto/ama/issues/22#issuecomment-208071065

## 

@toddmotto

**Comment by whizkydee** [comment]
Much thanks @toddmotto for your time. :heart:. I'll check that.
