### ISSUE TITLE
What's a normal day in your life?

### ISSUE THREAD

**Issue by tiagomsmagalhaes** [toddmotto/ama#24]
Hi,

After reading your blog post about your diet, and led my to asking, how it's your usual work day and time scheduling.

Thanks in advance,
Tiago

**Comment by toddmotto** [comment]
Hey Tiago, so right now I'm in between moving house and just started a new job role as Developer Advocate at Telerik, so things aren't as routine as usual with working out etc. But anyway, I work 9-5.30ish so usual workdays, and fit in fitness around that :)
