### ISSUE TITLE
Angular Architecture : service placement

### ISSUE THREAD

**Issue by timothylombrana** [toddmotto/ama#26]
Hey @toddmotto, 

Don't know if you already have a similar question answered or a post but I'd like to know more about setting up large project architecture. For now specifically placing the service inside model(as a chained method), agree or disagree, why? Thanks, and cheers!

**Comment by toddmotto** [comment]
Hey, would you be able to provide some more info / maybe some architecture examples and code flow etc?

**Comment by timothylombrana** [comment]
Hey, yes certainly. Basically is the service in Angular considered the model?  I only ask is because I've seen it used this way For example this is the way I define my service, but I'll include the way I've seen them written. Please let me know which is the best/preferred for all extensive purposes. Thanks!

```
//My example which is namely ExampleService.
function ExampleService (){
'use strict';
console.log('ExampleService')';
}

module.exports = function(ngModule){
ngModule.service('ExampleService', ExampleService);
};


//Others example which the service used as a model.
angular
.module('app')
.service('OthersExampleModel', function () {
    console.log('OthersExampleModel');
});
```

**Comment by toddmotto** [comment]
So, a model in my opinion is the data that is kept in sync inside the controller, but fetched _from_ a service.

Runtime:
- Angular loads the page
- Controller gets instantiated
- Controller asks for data from service
- Controller gets data, passes to view via $scope/this binding
- From here, model is synced by View and Controller via two-way model bindings. Model updates (from service) will trigger a Controller refresh, and View updates from user input will trigger Controller refresh to update the data again

So really, a Service should provide you the data, but then inside the Controller, you either make a _copy_ of it or assign the response from the Service to a Controller property. Hope that makes some sense!

**Comment by timothylombrana** [comment]
100%! Thanks for the clarification.

**Comment by toddmotto** [comment]
You're welcome, have a good'n :)
