### ISSUE TITLE
Looking for a technical co-founder - what are your suggestions?

### ISSUE THREAD

**Issue by hahahello** [toddmotto/ama#27]
Dear Todd,

I was browsing through GitHub and saw your profile/twitter/website. I am very impressed with your work!

Who am I? A passionate designer/marketer looking for a long-time buddy to make a start-up with.

That being said, I think you might have a good answer for this: 

What is a tried and true way to find a technical co-founder for a start-up you're working on? 

Let's say the person has not just an app idea, but a live app in the App Store, a business plan, 10k+ downloads, traction, and revenue.

Although this question has been asked many times before, I'm wondering if you have any advice.

I appreciate your help and hope others can also benefit from this question!

**Comment by toddmotto** [comment]
Hey, sorry I'm not really gonna be much help on this - literally no idea as never done it! Good luck with your project though, all the best :)
