### ISSUE TITLE
What is one thing about yourself that others would be shocked to know?

### ISSUE THREAD

**Issue by mxstbr** [toddmotto/ama#29]
;)

**Comment by toddmotto** [comment]
I occasionally listen to Justin Bieber.

**Comment by mxstbr** [comment]
Oh god Todd. That's it, I can't do this. Justin Bieber?!?! It's over!

**Comment by mxstbr** [comment]
_(I do too sometime, his new stuff kinda actually is good)_

**Comment by mxstbr** [comment]
It's fascinating how he managed to successfully complete the jump from hated-kiddie-star to loved-mainstream-megastar. I'm sure there's a story somewhere in there and I'd love to know it.
