### ISSUE TITLE
Does one ever overcome the feeling of not being an expert? 

### ISSUE THREAD

**Issue by jcsrb** [toddmotto/ama#3]

**Comment by toddmotto** [comment]
I don't think so, I wouldn't class myself an expert by any means. I'm just passionate about certain things, love teaching, writing and talking about it too. I don't think I'll ever get to where I "want to be" in terms of knowledge, and that's something I wish I could entirely devote all my time to do and share learnings with everyone else, through writing and training/workshops! :)
