### ISSUE TITLE
What songs are your current jam?

### ISSUE THREAD

**Issue by mxstbr** [toddmotto/ama#30]
(except Justin Bieber obv)

**Comment by toddmotto** [comment]
Currently obsessing with:
- The Monster - Rihanna/Eminem 
- Falling - HAIM
- NWA - Gangsta Gangsta
- No Vaseline - Ice Cube
- Fuck Tha Police - NWA
- Your Love - Outfield
- Friday I'm In Love - The Cure
- Boyz-N-The-Hood - Eazy E

I have a gangsta and oldschool side :D with a penchant for incredible female vocals.
