### ISSUE TITLE
Which is your preferred method of dependency injection?

### ISSUE THREAD

**Issue by timothylombrana** [toddmotto/ama#35]
$Inject vs @ngInject: Which is your preferred and most performant choice on dependency inject? For production large scale application.

**Comment by toddmotto** [comment]
If I'm not mistaken, `@ngInject` will annotate the functions for you (sometimes using `$inject` or the Array syntax), whereas `$inject` is something you'd do yourself and is faster. See this for more, I broke down the process: https://toddmotto.com/angular-js-dependency-injection-annotation-process/

**Comment by timothylombrana** [comment]
Thanks Todd! Much appreciated, great article.

**Comment by toddmotto** [comment]
Anytime! :)
