### ISSUE TITLE
Angular 1.3.* Event listener for Ajax call

### ISSUE THREAD

**Issue by timothylombrana** [toddmotto/ama#38]
Suppose I need to fire a function every time there was an $http request being made. What would be your angular-way of doing this?

**Comment by toddmotto** [comment]
Hey man. So, what I'd probably have is something like this:

``` js
function MyService($http, $rootScope) {
  function doSomething(data) {
    $rootScope.$emit('http:stuffAboutToHappen' [, data ]);
    return $http.get('/url').then(function (response) {
      $rootScope.$emit('http:stuffHappened' [, data ]);
      return response.data;
    };
  }
  return {
    doSomething: doSomething
  };
}
```

Then listen to `$rootScope.$on('http:stuffAboutToHappen', function (event, data) {...});` in your Controller :) hope that helps.

**Comment by timothylombrana** [comment]
Thanks so much for the quick response, next time your in Austin pints are on me! Could this apply to a catch all request made, so if the request was made from a different view and wanted to emit there has been a request and catch it on a completely different view. I need to invalidate cache, so trying to do a catch all event on all http calls.

**Comment by toddmotto** [comment]
If you want to capture view events, check out the events ui-router emits, `stateChangeStart` and success and so on. There's also HTTP Interceptors that you can jump into as well :) pint in Austin sounds awesome man! Loved that place so much.

**Comment by timothylombrana** [comment]
Cheers! Thanks Todd!

**Comment by toddmotto** [comment]
:D you're welcome!
