### ISSUE TITLE
Angular 2 + RequireJS

### ISSUE THREAD

**Issue by Franziskus1988** [toddmotto/ama#41]
Hi, 
I'm trying to set up Angular 2 with RequireJS, but can't get it running. Do you have an example project on how to do this. I only find example projects that are using System. Since I have a relatively big requirejs+angular1 web-app running, I can't easily switch my module loader. Generally the angular team could offer more information on how to use other module loaders. 

Hope you have a good advice. 

Regards,
Franziskus

**Comment by bhabanipattanayak** [comment]
hi
did you get anything for your question

**Comment by luboid** [comment]
https://github.com/luboid/requirejs-angular-router
