### ISSUE TITLE
$parse:lexerr

### ISSUE THREAD

**Issue by Nastia-R** [toddmotto/ama#43]
Hi, can you help me with some angular problem, please? 

We have items table in db, in which is characteristics field, which contains html, some special chars (like &copy; ). For some reasons we cann't change this db structure.

I've read abput this error, but still cann't fixe this $parse:lexerr error. Dump with this data right before output to frontend seems ok. What can be wrong with parsing than? This is angular error link: https://goo.gl/jKSE8B

Looking forward for your answer!

**Comment by toddmotto** [comment]
Sorry can't really do much with this
