### ISSUE TITLE
What do you make in USD?

### ISSUE THREAD

**Issue by f00Dev** [toddmotto/ama#44]
Hello Todd,

What do you make in the industry, and do you feel that your salary commensurate's with your experience?

Thanks!

**Comment by toddmotto** [comment]
I make a good living, I also do a lot of freelance/training work (courses/one-to-one training/workshops as well as little things like blog advertising revenue [only around $120/month but it all adds up]). I don't really know the exact figures as it's fluctuating all the time, and I won't share my salary from my day job as that's a little more sensitive. I'm guessing $250-300k total by the end of the year. Having the financial buffer isn't a goal/target thing for me though, it allows me to pursue other things such as spending 6 months not doing training, and then building new courses for example to be able to help others in the industry and share knowledge, as that's what I'm really passionate about :)
