### ISSUE TITLE
angular-styleguide HTML

### ISSUE THREAD

**Issue by blowsie** [toddmotto/ama#45]
Some IDE's, namely Webstorm only offer partial support for HTML inside JS files, for example automatic code formatting does not work.

I would like to have my component /  directive HTML inside its own HTML file.

Doing this causes some issues when using systems such a Webpack, as the files are not automatically added to the template cache.
- What is your opinion on separating out the HTML from the JS file? (Good/Bad/Ugly?)
- Is there a smart way to add the HTML files to the template cache?

Thanks

**Comment by toddmotto** [comment]
Literally about to take off for a 3 hour plane ride. Check out ngTemplate cache or something similarly named. For grunt and gulp etc :) 

@toddmotto

**Comment by blowsie** [comment]
Thanks Todd, I'll take a look at using https://github.com/WearyMonkey/ngtemplate-loader or similar.

I think having these files separated in my large application is going to be much more maintanable. Should be better for VCS too :+1:
