### ISSUE TITLE
What do you think of Web Components?

### ISSUE THREAD

**Issue by benoror** [toddmotto/ama#5]
Particularly, do you see it as the future for a more modular & simplified (web-)development?

**Comment by toddmotto** [comment]
I wouldn't say it was simplified at all!

I've had this conversation with many people too, even with a Polymer core team members at Google IO a few years back. I went home and [tried Polymer](https://github.com/toddmotto/fluidvids-polymer) on an existing OS project to get a real grip of the concepts behind Web Components and make an educated argument for discussions for/against it and it's concepts. I also wrote an [introductory article](http://toddmotto.com/web-components-concepts-shadow-dom-imports-templates-custom-elements) on it.

In brief; I love Web Components, however their adoption is somewhat hindered by the broadness of the spec and time taken to implement it. By this time, we've already built far superior JavaScript tools and compilers/wrappers that do a far better job. Saying that, adopting Web Components features (such as Angular making use of ShadowDOM) is a fantastic step forward for web tech!

**Comment by benoror** [comment]
Great :+1: Thanks!

**Comment by benoror** [comment]
BTW, what do you think of the limitation to pass **strings-only** to components' attributes:

> When Sebastian Markbage (one of React’s creators) was asked about Web Components, he answered:
> 
> > ... **How do you pass data when everything is a string?**...

Source: [www.2ality.com/2015/08/web-component-status.html](http://www.2ality.com/2015/08/web-component-status.html)

More specifically, do you see **web components complementing JS frameworks**, or even **replacing them completely in the mid-term**?

**Comment by toddmotto** [comment]
Wow, comments are extremely interesting in that thread.

I said above "we've already built far superior JavaScript tools and compilers/wrappers that do a far better job", my short and best answer is that I don't think anyone within the next 5 years will actually be doing this in production:

``` html
<link rel="import" href="google-map.html">
<google-map></google-map>
```

... Unless you work at Google haha :P

**Comment by benoror** [comment]
:laughing: for the sake of context:

https://twitter.com/toddmotto/status/677218985495166976

@toddmotto interesting stuff, thanks!
