### ISSUE TITLE
Search on site

### ISSUE THREAD

**Issue by tmgriffith** [toddmotto/ama#55]
Just some helpful feed back, If possible, due to the amount of posts on your site, you should implement a search tool so it is easier to find helpful info you have posted

**Comment by toddmotto** [comment]
Hey Timothy! :) yeah I fully agree. I actually had a look at it today, I'm working on it! :) will leave this open until I've merged it.

**Comment by toddmotto** [comment]
Added search :)

**Comment by tmgriffith** [comment]
Sweet! Thank you for quality resources you have provided! It has helped me tremendously over the last couple of months.

On Oct 24, 2016, at 5:05 AM, Todd Motto <notifications@github.com<mailto:notifications@github.com>> wrote:

Added search :)

##

**Comment by toddmotto** [comment]
Ah dude honestly that's super kind. Thanks so much for saying that :)! 

@toddmotto
