### ISSUE TITLE
Coming to England

### ISSUE THREAD

**Issue by JimLynchCodes** [toddmotto/ama#56]
Hey Todd Motto!

Wow, I am a huge fan of all of your blog posts and videos that you put out. They really helped me in getting started with AngularJS, and the way to explain the concepts really makes many difficult concepts understandable. I used your style guide a ton back in the heyday of AngularJS. I'm also a relatively young developer who has been coding for years and is trying to hone my front-end skills to build great virtual experiences. I'm trying to position myself a speaker, teacher, and famous front-end developer of NYC, maybe one day becoming a Google advocate or GDE.

I'm going to the Firebase summit in Berlin, but I'll be visiting my sister in London from Nov 2nd - 6th. I'd love to come take an Ultimate Angular in-person class or buy you a few drinks while I'm there!

- Jim

**Comment by toddmotto** [comment]
Hey dude! 💃  thanks for the kind words! Glad the styleguide has been really useful to you. I live about 3 hours away from London and sadly won't be down there - when you're back next let me know in advance and we'll grab a beer! :D

**Comment by JimLynchCodes** [comment]
Cool. I'll for sure let you know when I'm back in the area!
