### ISSUE TITLE
console.log() in production

### ISSUE THREAD

**Issue by ghost** [toddmotto/ama#58]
I'm a lover of `console.log()` for Dev but it can be a pest to find and either remove or comment out each one in an SPA.

Do you have any tricks or guidelines on handling `console.log()` when going into Prod?

**Comment by toddmotto** [comment]
Not sure which build processes you're using, but I used to use one of these (can't remember exactly) for gulp :) https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=gulp%20remove%20console.log
