### ISSUE TITLE
Hello, I need your permission.

### ISSUE THREAD

**Issue by han41858** [toddmotto/ama#59]
Hi. I'm Janghyun Han, programmer in South Korea.
And I'm a admin in GDG Korea Web Tech session.

I read your GREAT article about Angular 1 and 2. I'm a big fan of Angular.

So, if you give me permission, I want to translate your article for people in my country.
I want translate your GOOD articles in Korean, and remain its original URI.

Please think positively!

Have a nice day,
Thanks!!

**Comment by toddmotto** [comment]
Absolutely, feel free - just a link back to the original post at the top/bottom of your article would be muchly appreciated :)

**Comment by han41858** [comment]
Thanks a lot!!!
