### ISSUE TITLE
To become an google developer expert.

### ISSUE THREAD

**Issue by rajasekarm** [toddmotto/ama#6]
Hey Todd, I am following your blog/twitter for a long time. Its very useful also. 
I have one question for you, I am a Front end engineer have depth knowledge in HTML5, CSS3 and JS.
I want to apply for google developer expert. Can you guide me?

Thanks!!

**Comment by toddmotto** [comment]
Hey @rajzshkr! Glad you like the blog :)

So, there are two ways you can "apply" (or rather, be recommended):
1) Google employee recommendation
2) Existing GDE recommendation

What you essentially need "to do" is share knowledge (though there is obviously no formula or guarantee to "get in" and getting into the GDE program was something I never aimed for), help others in multiple different ways.

Ways of sharing/helping:
- Blogging
- Writing books
- Helping on Twitter
- Helping on StackOverflow
- Talking at conferences
- Giving workshops
- Aiming to teach people things in any way you can think of! :)
