### ISSUE TITLE
Confused, need some guidance.

### ISSUE THREAD

**Issue by scribbyx** [toddmotto/ama#61]
Hey Todd!

I am a huge fan of your blog and your work! 
I just completed learning basic native JS and am now confused as to what learning path I should follow. 
I want to be a UX/UI developer. Should I stick to native JS and just keep getting better at it? or should I start with jQuery? Also, what should I do/know before I try dipping my feet into Angular?

Thank you.

**Comment by toddmotto** [comment]
Pick a few things you want to build, such as a drop down navigation and keep building, you'll only get better the more you build! :) You'll learn lots. Once you've got a good understanding of loops, arrays, objects, functions and conditionals in JavaScript then I'd recommend looking at a framework to build web applications with - but make sure you've got a fundamentals understanding of the DOM beforehand and good JavaScript skills! :)
