### ISSUE TITLE
Hi Todd!

### ISSUE THREAD

**Issue by juliosguz** [toddmotto/ama#62]
Hello!

My name is Julio Silva and I am official organizer of GDG Cochabamba in Bolivia.

I was read many of your articles, they are great. We are about to open the blog of our community and one of the contributions that I would like to do is the translation of some of your post to Spanish. It's possible?

Obviously, I will add the link to original post.

Have a nice day :D

**Comment by toddmotto** [comment]
Sure thing my friend :) appreciate it!

**Comment by juliosguz** [comment]
Thanks man! Our community will sure appreciate it
I will keep you posted :)
