### ISSUE TITLE
How to get that "shiny-code-line" effect from your presentations?

### ISSUE THREAD

**Issue by FabianGosebrink** [toddmotto/ama#69]
Hello Todd,

first of all: Thank you for your amazing work, your amazing talks. 

I am a speaker too and want to get my slides going with reveal.js. I love the effect you had on your forms- talk at the ng-be 2016.

![image](https://cloud.githubusercontent.com/assets/11268349/22930018/acce6710-f2be-11e6-92fe-4f67018fc942.png)

How did you get that?

Or: Are the HTML Sources to your talks available anywhere?

BR

Fabian

**Comment by toddmotto** [comment]
Hey Fabian! Thanks for the kind words my friend! :)

So, I use this as the slides boilerplate:
https://github.com/FormidableLabs/spectacle-boilerplate

And for the interactive slides:
https://github.com/thejameskyle/spectacle-code-slide

Let me know how you get on with them! :) good luck

**Comment by FabianGosebrink** [comment]
Hey Todd,

perfect, exactly what I was searching for. 

Thanks you!

**Comment by FabianGosebrink** [comment]
Hey Todd,

may it be that you went with spectacle in Version 1.x? Because Version 2 seems not to be compatible with the spectacle-code-slide current version :(

BR

**Comment by toddmotto** [comment]
Not sure - double check with the authors of the projects :)

**Comment by FabianGosebrink** [comment]
Yeah, got it working with previous versions which are compatible. Thank you! Owe you a beer if I will be in London some day :)

**Comment by toddmotto** [comment]
Sounds good to me! I owe you one back for not updating my local code to the latest version right before the next conference! :P
