### ISSUE TITLE
Doggie

### ISSUE THREAD

**Issue by GregTrevellick** [toddmotto/ama#7]
Great night at So'ton Todd yesterday - thx !  In the spirit of ama, got an elderly Cocker myself, how's life with a nipper Rottie ? Cheers, Greg

**Comment by toddmotto** [comment]
Hey Greg! Thanks for attending the session :)!

So, they're actually my mums dogs, she has 3 Rottweilers, one 9 months, one about 3/4 years and a 8/9 year old. They're the best dogs I've met, super kind!
