### ISSUE TITLE
Subscribing to event emitter

### ISSUE THREAD

**Issue by ghost** [toddmotto/ama#78]
Hey Todd,

First off, thanks for the Ultimate Angular course. It's great reference material and has taught me a lot I may have skipped over when learning Angular!

Secondly, in your pro course, while talking about Inputs and Outputs on dynamic components, you subscribe to a component's event emitter.  I had been following the advice from https://www.bennadel.com/blog/3038-eventemitter-is-an-rxjs-observable-stream-in-angular-2-beta-6.htm#comments_47949 and not subscribing manually. I realize that this was pre-release advice, but they have never updated their stance. What are your thoughts on this matter? Does it seem like the team will continue to use observables here?

**Comment by toddmotto** [comment]
Hey @solanaprojordan! Glad you're making great use of the course! I've had a few others reach out about the same topic - so it's definitely a great question! I did in fact speak to a core team earlier this year and the feedback was along the lines of "We want to make Angular more reactive, not less!". So I'd 100% say it's good to roll with for as long as I can forsee.

Let's assume that it was changed though, an EventEmitter is also very similar to a Subject - which you could always use. Try it in your code next time to see how it's a direct replacement:

```js
@Output() prop = new Subject<string>();
```

**Comment by ghost** [comment]
Thanks!  Looking forward to your ngrx stuff.

-Jordan
