### ISSUE TITLE
HTML5 Geolocation Database

### ISSUE THREAD

**Issue by ExeFormWebChannel** [toddmotto/ama#9]
Hi,
I was reading the interesting article "Using HTML5 Geolocation to show current location with Google Maps API".
I would like to know if all positions can be saved in a database like MySQL. 
I am involved in a crowd density project. 
And this feature can be really useful.

Thanks
Best
Joseph Caristena
Email: info@exeform.it
ITALY
www.egovmetrics.com
Mobile +39 349 1456195

...

**Comment by toddmotto** [comment]
Of course, you'll just need to fetch positions, save them on the backend and return them again.
